#!/usr/bin/env bash
# Script to query subdomains for a domain and print their DNS information

domain=$1
subdomain=$2

function get_subdomain_info {
    local sub=$1
    local dom=$2
    result=$(dig "${sub}.${dom}" +short | awk 'NR==1 {print $0}')
    if [ -z "$result" ]; then
        echo "The subdomain ${sub} does not exist."
    else
        echo "The subdomain ${sub} is a A record and points to ${result}"
    fi
}

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info "$sub" "$domain"
    done
else
    get_subdomain_info "$subdomain" "$domain"
fi
