#!/bin/bash

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$IP:~/"

if [ $? -eq 0 ]; then
    echo "File successfully transferred to $USERNAME@$IP:~/"
else
    echo "Failed to transfer file."
    exit 1
fi
