#!/usr/bin/env bash
# Installs and configures Nginx on an Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo touch /var/www/html/index.html
sudo echo  "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
