#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another URL

# Backup the default Nginx configuration file
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Add redirection configuration
sed -i '/server_name _;/a \\tlocation /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
