#!/usr/bin/env bash
# This script answers questions related to types of networks.
# 1. A computer in a local network is connected to: LAN
# 2. A network that connects an office in one building to another office a few streets away: WAN
# 3. Network used when browsing www.google.com from a smartphone (not connected to Wifi): Internet
2
1
