#!/usr/bin/env bash
# This script answers questions related to MAC and IP addresses.
# 1. What is a MAC address? The unique identifier of a network interface.
# 2. What is an IP address? Is to devices connected to a network what postal address is to houses.
2
1
