#!/usr/bin/env bash
# Fix Nginx to listen on port 80 in 5 lines or less
sudo sed -i '/listen \[::\]:80 default_server;/a \    listen 80 default_server;' /etc/nginx/sites-enabled/default
sudo systemctl restart nginx
service nginx status
