#!/usr/bin/env bash
# Ensure Nginx listens on port 80 and serves the default page
sed -i '/listen \[::\]:80 default_server;/a\    listen 80 default_server;' /etc/nginx/sites-enabled/default
sudo systemctl stop nginx
sudo systemctl start nginx
curl -s 0:80 | grep "Welcome to nginx"
