#!/usr/bin/env bash
# This script groups Apache log entries by IP and HTTP status code and sorts by occurrence count

awk '{count[$1 " " $9]++} END {for (entry in count) print count[entry], entry}' apache-access.log | sort -nr
