#!/usr/bin/env bash
# This script changes the IP resolution for localhost and facebook.com
# Backup the original hosts file

cp /etc/hosts ~/newhost
sed -i s/127.0.0.1/127.0.0.2/ ~/newhost
echo "8.8.8.8 facebook.com" >> ~/newhost
cp -f ~/newhost /etc/hosts
