#!/usr/bin/env bash
# This script changes the IP resolution for localhost and facebook.com

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Modify /etc/hosts
sudo sed -i '/127.0.0.1 localhost/d' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
