#!/usr/bin/env bash
# Fix Nginx to run as nginx user and listen on port 8080

sed -i 's/user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 /listen 8080 /g' /etc/nginx/sites-enabled/default
systemctl restart nginx
