#!/usr/bin/env bash
# Connects to the server using the private key ~/.ssh/school and the IP provided as an argument

if [ -z "$1" ]; then
  echo "Usage: $0 <server-ip>"
  exit 1
fi

ssh -i ~/.ssh/school ubuntu@"$1"
